### ISSUE TITLE
Container component should only exist once.

### ISSUE THREAD

**Issue by YuriDevAT** [YuriDevAT/from-zero-to-hero#2]
To prevent repetition, the container component should receive its content dynamically.

## Acceptance criteria

- [ ] Only one container component should exist.

**Comment by voidlaszlo** [comment]
@YuriDevAT I replaced enhancement label with refactor label. Enhancement is for new features/requests there. I think the correct one is refactor here. 😃

**Comment by YuriDevAT** [comment]
Sure 🙂
