### ISSUE TITLE
Replace .js with .ts

### ISSUE THREAD

**Issue by voidlaszlo** [YuriDevAT/from-zero-to-hero#5]
Replace all **_.js_** extensions with **_.ts_**. In a typescript project normally there shouldn't be any **_.js_** files.

**Comment by YuriDevAT** [comment]
Do you mean the tailwind.config files? It seems like they always stay as .js files, after looking at documenation or other projects.

**Comment by voidlaszlo** [comment]
I think if you use typescript in a project, you can just make them .ts. In GitHub theres 440 repositories where they use .ts extension for tailwind config. But it's a small thing, if you wan't to keep it like this, it should be okay too. I know some typescript compilers must be configured specifically if you use .ts and .js in the same project. 😊

TLDR:
.js should be fine. I mentioned .ts because of uniformity😁

**Comment by voidlaszlo** [comment]
Change not needed, i've found a lot of repos where people use config files with .js extension. It shouldn't make a difference.

**Comment by YuriDevAT** [comment]
Ok. I always got an error when changing the postcss config file but haven't look into it more deeply.

**Comment by voidlaszlo** [comment]
Yeah leave it like that, you are right. My mistake. :)
